import type { BrokerDirectLoginConnector, CanonicalHoldingRow, ExchangedToken } from "../../api-connector";
import type { CanonicalExecutionRow } from "../../adapter";

/**
 * DhanHQ v2 API — Direct Access Token method (dhanhq.co/docs/v2/authentication).
 * Unlike the older Partner API consent flow, this needs no registered app at
 * all: any Dhan account holder generates their own personal access token
 * themselves (web.dhan.co -> Profile -> Access DhanHQ APIs), valid 24 hours,
 * alongside their own Dhan Client ID — the same "each user brings their own
 * credential" model as Angel One/Kotak, not a platform-owned OAuth app.
 * Endpoints/headers/response fields verified directly against Dhan's own v2
 * docs (Authentication, Orders/Trade Book, Portfolio/Holdings pages) — not
 * guessed.
 */
const DHAN_API_ROOT = "https://api.dhan.co/v2";

async function dhanApiRequest<T>(path: string, accessToken: string): Promise<T> {
  const response = await fetch(`${DHAN_API_ROOT}${path}`, {
    headers: { "Content-Type": "application/json", "access-token": accessToken },
  });
  const json = await response.json();
  // Temporary diagnostic: a real account with confirmed holdings synced as
  // "0 holdings" with no error at all — need to see exactly what Dhan's API
  // actually returned (status + raw shape) to tell an empty-but-valid
  // response apart from a wrong-token-scope or unexpected-shape issue.
  console.warn(`[dhan-connect] ${path} -> status ${response.status}, ok=${response.ok}`, JSON.stringify(json).slice(0, 1000));
  if (!response.ok) {
    throw new Error(`Dhan API error (${response.status}): ${json.errorMessage ?? json.message ?? response.statusText}`);
  }
  return json as T;
}

interface DhanTradeRecord {
  dhanClientId: string;
  orderId: string;
  exchangeOrderId: string;
  exchangeTradeId: string;
  transactionType: "BUY" | "SELL";
  exchangeSegment: string;
  productType: string;
  tradingSymbol: string;
  securityId: string;
  tradedQuantity: number;
  tradedPrice: number;
  isin?: string;
  exchangeTime?: string;
  createTime?: string;
}
interface DhanHoldingRecord {
  tradingSymbol: string;
  isin?: string;
  exchange: string;
  totalQty: number;
  avgCostPrice: number;
  lastTradedPrice?: number;
}

function splitDhanSegment(raw: string): { exchange: string; segment: string } {
  const upper = (raw || "NSE_EQ").toUpperCase();
  const [exchange = "NSE", segCode = "EQ"] = upper.split("_");
  const map: Record<string, string> = { EQ: "EQ", FNO: "FUT", FO: "FUT", CURRENCY: "CUR" };
  return { exchange, segment: map[segCode] ?? segCode };
}

export const dhanConnector: BrokerDirectLoginConnector = {
  brokerCode: "DHAN",

  // "Configured" is now a per-connection question (does this user's stored
  // connection have its own access token?), not a server-wide one — always
  // show the connect form and let login()/fetch calls raise a specific
  // error if a token is actually missing or invalid.
  isConfigured(): boolean {
    return true;
  },

  /**
   * credentials: { accessToken, dhanClientId } — both self-generated by the
   * user from their own Dhan account (web.dhan.co -> Profile -> Access
   * DhanHQ APIs), used once, never re-derived. There's no login API call to
   * make here (unlike Angel One/Kotak) since Dhan already handed the user a
   * valid token directly — this just stores it; a bad token surfaces on the
   * very next sync call instead of a separate up-front validation request.
   */
  async login(credentials: Record<string, string>): Promise<ExchangedToken> {
    const { accessToken, dhanClientId } = credentials;
    if (!accessToken || !dhanClientId) {
      throw new Error("Access token and Dhan Client ID are both required.");
    }

    // Dhan's direct access tokens are valid 24 hours from generation — we
    // don't know the exact generation time, so this is a conservative
    // same-day expiry, matching the pattern used for Angel One/Kotak.
    const expiresAt = new Date();
    expiresAt.setUTCHours(24 + 0, 30, 0, 0);
    if (expiresAt.getTime() < Date.now()) expiresAt.setUTCDate(expiresAt.getUTCDate() + 1);

    return {
      accessToken,
      expiresAt,
      brokerUserId: dhanClientId,
      session: { dhanClientId },
    };
  },

  async fetchTodaysTrades(accessToken: string): Promise<CanonicalExecutionRow[]> {
    const trades = await dhanApiRequest<DhanTradeRecord[]>("/trades", accessToken);
    return trades.map((t) => {
      const { exchange, segment } = splitDhanSegment(t.exchangeSegment);
      return {
        symbol: t.tradingSymbol,
        isin: t.isin ?? null,
        exchange,
        segment,
        series: null,
        side: t.transactionType,
        quantity: t.tradedQuantity,
        price: t.tradedPrice,
        brokerTradeId: t.exchangeTradeId,
        brokerOrderId: t.orderId,
        executedAt: new Date(t.exchangeTime ?? t.createTime ?? Date.now()),
        raw: t as unknown as Record<string, string>,
      };
    });
  },

  async fetchHoldings(accessToken: string): Promise<CanonicalHoldingRow[]> {
    const holdings = await dhanApiRequest<DhanHoldingRecord[]>("/holdings", accessToken);
    return holdings.map((h) => ({
      symbol: h.tradingSymbol,
      isin: h.isin ?? null,
      // Verified against a real response: Dhan's holdings endpoint reports
      // "ALL" as the literal exchange value (equity demat holdings settle
      // across NSE/BSE together), not an actual exchange code — passing
      // that straight through left every holding unmatched against our
      // Exchange table, which only has real codes (NSE/BSE/MCX). NSE is the
      // correct default for equity holdings, same assumption CSV import
      // already makes when a row doesn't specify one.
      exchange: h.exchange && h.exchange !== "ALL" ? h.exchange : "NSE",
      quantity: h.totalQty,
      avgCostPrice: h.avgCostPrice,
      lastPrice: h.lastTradedPrice ?? null,
      previousClose: null, // not present in Dhan's v2 holdings response — see Angel One's connector for the pattern once a broker provides this
    }));
  },
};
