import type { BrokerDirectLoginConnector, CanonicalHoldingRow, ExchangedToken } from "../../api-connector";
import type { CanonicalExecutionRow } from "../../adapter";

/**
 * Upstox live API v2. Endpoints/header format verified directly against the
 * official upstox/upstox-nodejs SDK source (github.com/upstox/upstox-nodejs
 * — src/ApiClient.js for the base URL and Authorization header,
 * src/api/PostTradeApi.js for the historical trades endpoint).
 *
 * Upstox's own docs (upstox.com/developer/api-documentation/authentication)
 * confirm a manual token path: any account holder can self-register a free
 * developer app at account.upstox.com/developer/apps under their own login,
 * then click "Generate" on that app to mint a personal access token
 * directly — "ideal for one-time or occasional API usage" per Upstox's own
 * docs — with no OAuth redirect dance and no password ever touching this
 * app. Neither fetch call below sends a client_id/secret at all (only
 * Authorization: Bearer <token>, confirmed against the SDK) — those are
 * only needed for the OAuth authorization_code exchange step, which this
 * connector doesn't do, so no platform-level app is needed here. Same
 * "each user brings their own credential" model as Angel One/Kotak/Dhan.
 *
 * Notably better than Kite Connect for backfill: /v2/charges/historical-trades
 * accepts a date range, not just "today".
 */
const UPSTOX_ROOT = "https://api.upstox.com";

async function upstoxRequest<T>(
  path: string,
  options: { accessToken: string }
): Promise<T> {
  const response = await fetch(`${UPSTOX_ROOT}${path}`, {
    headers: { Accept: "application/json", Authorization: `Bearer ${options.accessToken}` },
  });
  const json = await response.json();
  if (!response.ok || json.status === "error") {
    const message = json.errors?.[0]?.message ?? json.message ?? response.statusText;
    throw new Error(`Upstox API error (${response.status}): ${message}`);
  }
  return (json.data ?? json) as T;
}

interface UpstoxTradeRecord {
  exchange: string;
  segment: string;
  quantity: number;
  trade_id: string;
  trade_date: string;
  transaction_type: "BUY" | "SELL";
  scrip_name: string;
  price: number;
  isin?: string;
  symbol: string;
}
interface UpstoxHoldingRecord {
  isin: string;
  product?: string;
  quantity: number;
  tradingsymbol?: string;
  trading_symbol?: string;
  last_price?: number;
  average_price: number;
  exchange: string;
}

export const upstoxConnector: BrokerDirectLoginConnector = {
  brokerCode: "UPSTOX",

  // "Configured" is now a per-connection question (does this user's stored
  // connection have its own access token?), not a server-wide one — always
  // show the connect form and let a sync call raise a specific error if a
  // token is actually missing or invalid.
  isConfigured(): boolean {
    return true;
  },

  /**
   * credentials: { accessToken } — self-generated by the user from their
   * own Upstox developer app (account.upstox.com/developer/apps -> the app
   * -> Generate), used once, never re-derived. There's no login API call to
   * make here (unlike Angel One/Kotak) since Upstox already handed the user
   * a valid token directly — this just stores it; a bad/expired token
   * surfaces on the very next sync call instead of a separate up-front
   * validation request.
   */
  async login(credentials: Record<string, string>): Promise<ExchangedToken> {
    const { accessToken } = credentials;
    if (!accessToken) {
      throw new Error("Access token is required.");
    }

    // Upstox access tokens expire at end of trading day (SEBI-driven daily
    // expiry, same regime as Kite Connect/Angel One/Kotak) — same "expires
    // at ~6am IST next day" convention used across every other connector.
    const expiresAt = new Date();
    expiresAt.setUTCHours(24 + 0, 30, 0, 0);
    if (expiresAt.getTime() < Date.now()) expiresAt.setUTCDate(expiresAt.getUTCDate() + 1);

    return { accessToken, expiresAt };
  },

  async fetchTodaysTrades(accessToken: string): Promise<CanonicalExecutionRow[]> {
    const today = new Date().toISOString().slice(0, 10);
    const params = new URLSearchParams({
      start_date: today,
      end_date: today,
      page_number: "1",
      page_size: "500",
    });
    const data = await upstoxRequest<{ trades: UpstoxTradeRecord[] }>(
      `/v2/charges/historical-trades?${params.toString()}`,
      { accessToken }
    );
    return (data.trades ?? []).map((t) => ({
      symbol: t.symbol,
      isin: t.isin ?? null,
      exchange: t.exchange.toUpperCase(),
      segment: t.segment.toUpperCase(),
      series: null,
      side: t.transaction_type,
      quantity: t.quantity,
      price: t.price,
      brokerTradeId: t.trade_id,
      brokerOrderId: t.trade_id, // verified response has no separate order_id field
      executedAt: new Date(`${t.trade_date}${t.trade_date.includes(":") ? "" : "T00:00:00+05:30"}`),
      raw: t as unknown as Record<string, string>,
    }));
  },

  async fetchHoldings(accessToken: string): Promise<CanonicalHoldingRow[]> {
    const holdings = await upstoxRequest<UpstoxHoldingRecord[]>("/v2/portfolio/long-term-holdings", { accessToken });
    return holdings.map((h) => ({
      symbol: h.tradingsymbol ?? h.trading_symbol ?? "",
      isin: h.isin ?? null,
      exchange: h.exchange || "NSE",
      quantity: h.quantity,
      avgCostPrice: h.average_price,
      lastPrice: h.last_price ?? null,
      previousClose: null, // not verified for this connector yet — see Angel One's connector for the pattern once it is
    }));
  },
};
